AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Says Hello World.

Properties:
  S3BucketName:
    Description: S3 bucket where code assets are stored
    Type: String
  S3KeyName:
    Description: S3 key name for stored code assets .zip
    Type: String


Resources:
  HelloWorldFunction:
      Type: AWS::Serverless::Function
      Properties:
          Handler: handler.Handle
          Runtime: python2.7
          CodeUri: ./dist/handler.zip
      Enviornment:
        Variables:
          HELLO: "Hello World, I am an Env Variable"
      
      # creates API Gateway Resource
      Events:
        GetHelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      
      # creates CodeDeploy resource preference
      AutoPublishAlias: Prod
      DeploymentPreference:
        Type: Canary50Percent10Minutes