AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Says Hello World.

Resources:
  HelloWorldFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: handler.Handle
        Runtime: python2.7
        CodeUri: ./dist/handler.zip
        # creates API Gateway Resource
        Events:
          GetHelloWorld:
            Type: Api
            Properties:
              Path: /hello
              Method: get
        # creates CodeDeploy resource preference
        AutoPublishAlias: Prod
        DeploymentPreference:
          Type: Canary10Percent5Minutes
      Enviornment:
        Variables:
          HELLO: "Hello World, I am an Env Variable"